apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: my-cluster
  namespace: my-cluster
  labels:
    cloud: aws
    region: ap-southeast-2
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
  annotations:
    argocd.argoproj.io/sync-wave: "460"
    helm.sh/hook-weight: "460"
spec:
  baseDomain: onetouchprovisioning.com
  clusterName: my-cluster
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    aws:
      credentialsSecretRef:
        name: my-cluster-aws-creds
      region: ap-southeast-2
  provisioning:
    installConfigSecretRef:
      name: my-cluster-install-config
    sshPrivateKeySecretRef:
      name: my-cluster-ssh-private-key
    imageSetRef:
      name: img4.9.56-x86-64-appsub img4.10.53-x86-64-appsub img4.11.31-x86-64-appsub img4.12.7-multi-appsub
  pullSecretRef:
    name: my-cluster-pull-secret
