apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: my-cluster
  namespace: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "460"
    helm.sh/hook-weight: "460"
spec:
  clusterName: my-cluster
  clusterNamespace: my-cluster
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
