apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: ap-southeast-2
    name: my-cluster
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: default # Leave as is for now..
  name: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "470"
    helm.sh/hook-weight: "470"
spec:
  hubAcceptsClient: true
