apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-cluster-aws-creds
  namespace: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
spec:
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: ade6c30f-97a9-87c8-31ea-fdd7e14598fd
    - secretKey: awsSecretKey
      remoteRef:
        key: 36d87095-a40d-aa4a-e110-7de764cb018b
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: my-cluster-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ .awsAccessKey | toString }}
        aws_secret_access_key: |-
          {{ .awsSecretKey | toString }}
