apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-ssh-private-key
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  data:
  - secretKey: openshiftSSHPrivateKey
    remoteRef: 
      key: 16d3cb8f-1514-b7b8-c9c3-8c085294c6ff 
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ "{{ .openshiftSSHPrivateKey | toString }}" }}
  