apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster }}-aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: e7e8a6c4-7e13-d961-3e2c-b73a1bb73658 
    - secretKey: awsSecretKey
      remoteRef:
        key: f0fb2319-46f4-9c71-577a-883d574e8c69
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsSecretKey | toString }}" }}