apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: scoobydoo
    cluster.open-cluster-management.io/managedCluster: scoobydoo
    kubernetes.io/metadata.name: scoobydoo
  name: scoobydoo
