apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-ryu-ssh-private-key
  namespace: test-ryu
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
spec:
  data:
    - secretKey: openshiftSSHPrivateKey
      remoteRef:
        key: edcc6329-e70b-0dfe-cc90-4996f3de877d
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: test-ryu-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ .openshiftSSHPrivateKey | toString }}
