apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-ryu-pull-secret
  namespace: test-ryu
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
spec:
  data:
    - secretKey: openshiftPullSecret
      remoteRef:
        key: d11eb84d-7a78-4dfd-0411-a32c3cae84c9
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: test-ryu-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ .openshiftPullSecret | toString }}
