apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterpoolName }}-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "310"
    helm.sh/hook-weight: "310"
  namespace: rhacm-clusterpools 
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef: 
      key: f9fcbfc5-6c62-e001-5a90-55401d1608d6
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterpoolName }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}   