apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: govtech
  namespace: govtech
  labels:
    cloud: aws
    region: ao-aoutheast-1
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
spec:
  baseDomain: onetouchprovisioning.com
  clusterName: govtech
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: govtech-aws-creds
      region: ao-aoutheast-1
  provisioning:
    installConfigSecretRef:
      name: govtech-install-config
    sshPrivateKeySecretRef:
      name: govtech-ssh-private-key
    imageSetRef:
      name: img4.9.56-x86-64-appsub
  pullSecretRef:
    name: govtech-pull-secret
