apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: ap-southeast-1
    name: govtech
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: default # Leave as is for now..
  name: govtech
  annotations:
    argocd.argoproj.io/sync-wave: "370"
    helm.sh/hook-weight: "370"
spec:
  hubAcceptsClient: true
