apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: ao-aoutheast-1
    name: govtech
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: default # Leave as is for now..
  name: govtech
spec:
  hubAcceptsClient: true
