apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: govtech
  namespace: govtech
  annotations:
    argocd.argoproj.io/sync-wave: "470"
    helm.sh/hook-weight: "470"
